# Required Swiftlint Version
# swiftlint_version: 0.34.0

# Paths to include in lint
included:
  - Demo
  - Sources
  - UnitTests
  
indentation: 4 # Indentation with 4 spaces
line_length:
  warning: 120 # Column line length
  ignores_comments: true
  ignores_urls: true
