name: Build
on: [pull_request, workflow_dispatch]
jobs:
  cocoapods:
    name: CocoaPods
    runs-on: macOS-11
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Run pod lib lint
        run: pod lib lint

    swiftlint:
    runs-on: macOS-11
    steps:
    - name: Check out repository
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run SwiftLint
      run: bundle exec fastlane lint
