name: SwiftLint
on: [pull_request, workflow_dispatch]
jobs:
  swiftlint:
    runs-on: macOS-11
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Install Dependencies
        run: bundle install
      - name: Run SwiftLint
        run: bundle exec fastlane lint

