name: Tests
on: [pull_request, workflow_dispatch]
jobs:
  unit_test_job:
    name: Unit
    runs-on: macOS-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Install Dependencies
        run: bundle install
      - name: Run Unit Tests
        run: bundle exec fastlane unit_tests

  code_coverage:
    name: Unit Test Coverage
    runs-on: macOS-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Install Dependencies
        run: bundle install
      - name: Calculate Unit Test Code Coverage
        run: bundle exec fastlane coverage
